### ISSUE TITLE
Tweaking the html output

### ISSUE THREAD

**Issue by sojusnik** [jaap-karssenberg/zim-desktop-wiki#96]
I'm trying to match the html output of a page (f.i. print) its initial state, read the normal editing view in Zim. So a normal text looks in Zim like [this](http://i.imgur.com/3aNiG8b.png), but in a print html export like [this](http://i.imgur.com/uFejdYL.png). As you can spot, the print view doesn't have a line break. Therefore I want to alter the `<br>` within `<p>`, that is responsible for the line break, but struggle to do so.

As for the line break itself, `margin-bottom: 0.5em` does it, but I don't know what to write into `~/.local/share/zim/templates/html/Print.html`. So does anybody know the proper command to address `<br>` within `<p>`?

**Comment by Osndok** [comment]
I sounds like what you need is a CSS style block in the header that has either an "p br" or "p > br" selector.

e.g.
```CSS
<html>
<head>
...
<style>
p br
{
    margin-bottom: 0.5em;
}
</style>
...
</head>
<body>
...stuff you cant change...
</body>
</html>
```

I hope I understood your question, and I hope that helps!
